[default]
LOAD_DOTENV = true

MAX_THREADS = 2
MAX_RETRIES = 3
TIME_BETWEEN_REQUESTS = [1, 3]  # Min e Max para random delay
BASE_URL = "https://apps.apple.com"

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
]

# MongoDB Configuration
MONGO_URI = "@env "
MONGO_DB_NAME = "scraper_data"

# Celery Configuration
CELERY_BROKER_URL = "@env"
CELERY_RESULT_BACKEND = "@env"

# Sensor Tower Configuration
SENSORTOWER_LOGIN = "@env"
SENSORTOWER_PASS = "@env"