"""create apps table

Revision ID: c403d6e2afc3
Revises: 
Create Date: 2025-03-24 00:46:06.963659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c403d6e2afc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apple_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('category_rank', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('list_type', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('has_in_app_purchases', sa.String(), nullable=True),
    sa.Column('monthly_revenue_estimate', sa.Float(), nullable=True),
    sa.Column('monthly_downloads_estimate', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('num_screenshots', sa.Integer(), nullable=True),
    sa.Column('rating_summary', sa.String(), nullable=True),
    sa.Column('latest_version', sa.String(), nullable=True),
    sa.Column('latest_version_date', sa.Date(), nullable=True),
    sa.Column('labels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('reviews', sa.JSON(), nullable=True),
    sa.Column('privacy_data', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('general_info', sa.JSON(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_apple_id'), 'apps', ['apple_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_apple_id'), table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###
