LOAD_DOTENV = true

# MongoDB
MONGO_URI = "@env"
MONGO_DB_NAME = "scraper_data"
MONGO_COLLECTION_NAME = "raw_apps"

# PostgreSQL
POSTGRES_URI = "@env"

# Celery
CELERY_BROKER_URL = "@env"
CELERY_RESULT_BACKEND = "@env"

# Transform config
MAX_RETRIES = 3
WORKER_CONCURRENCY = 4
BATCH_SIZE = 50
