LOAD_DOTENV = true

# MongoDB
MONGO_URI = "@env"
MONGO_DB_NAME = "scraper_data"
MONGO_COLLECTION_NAME = "raw_apps"

# PostgreSQL
POSTGRES_URI = "@env"

# Celery
CELERY_BROKER_URL = "@env"
CELERY_RESULT_BACKEND = "@env"

OPENAI_API_KEY = "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"

# Transform config
MAX_RETRIES = 3
WORKER_CONCURRENCY = 4
BATCH_SIZE = 50
