# settings.toml

[default]
LOAD_DOTENV = true

# MongoDB
MONGO_URI = "mongodb://mongo:27017"
MONGO_DB_NAME = "scraper_data"
MONGO_COLLECTION_NAME = "raw_apps"

# PostgreSQL
POSTGRES_URI = "postgresql://postgres:postgres@postgres:5432/analytics_db"

# Celery
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/1"

# Configurações de transformação
MAX_RETRIES = 3
WORKER_CONCURRENCY = 4
BATCH_SIZE = 50
